from setuptools import setup

setup(
    name='nntemplate',
    version='0.5.0',
    description='Bundle of usefull tools for training segmentation or image classification neural networks. Including: configuration parser, log to wandb, hyper-parameter search with optuna, dataloader and data-augmentation...',
    url='https://github.com/gabriel-lepetitaimon/nn-template',
    author='Gabriel Lepetit-Aimon',
    author_email='gabriel.lepetit-aimon@polymtl.ca',
    license='BSD 2-clause',
    package_dir = {'': 'lib'},
    packages=['nntemplate'],
    python_requires='>3.10',
    install_requires=['numpy',
                      'torch',
                      'torchvision',
                      'torchgeometry',
                      'pytorch-lightning',
                      'torchmetrics',
                      'wandb',
                      'albumentations',
                      'opencv-python-headless',
                      'pyyaml',
                      'segmentation-models-pytorch',
                      'parse',
                      'optuna',
                      'webcolors',
                      'ttach',
                      'pandas'
                      ],
)
