experiment:
    project: "WandB Project Name"
    name: "Run Name"
    tags: []      # WandB run tags (optional)

    wandb:
        entity:    # WandB entity where the run should be registered (optional)

        group:     # WandB run group (optional)
        job-type:  # WandB run job-type (optional)

        notes:     # WandB run notes and comments (optional)
        dir:       # WandB run artefact directory (optional)




###########################################################
#         ---   HYPER-PARAMETER SEARCH   ---              #
###########################################################
optuna:
    study_name: 'test'
    storage: 
    n_runs: 20
    sampler:
        type: TPE
        n_startup_trials: 10
    pruner:
        type: Hyperband
        monitor:


###########################################################
#                    ---   TASK   ---                    #
###########################################################
task:
    type: Segmentation2D
    n-classes: binary

    loss: cross-entropy #(eval?)

    optimizer:
        type: Adam
        #weight_decay: 0
        #beta: 0.9       # coefficients used for computing running averages of gradient
        #beta_sqr: 0.999 # and its square
        #amsgrad: True

        lr: ~optuna.float(1e-5,1e-2)

    metrics: kappa, acc, confmat, iou, auroc

###########################################################
#                    ---   MODEL   ---                    #
###########################################################
model:
    type: 'smp'
    architecture: 'Unet'
    encoder_name: 'resnet34'
    encoder_weights: 'imagenet'
    # See https://smp.readthedocs.io/en/latest/models.html


###########################################################
#                   ---   TRAINING   ---                  #
###########################################################
training:
    minibatch: 8
    gradient-clip: 2
    max-epoch: 30
    seed: 1234

    validate-every-n-epoch: 1
    objective: val-acc
    direction: max

    checkpoints: train-loss^, val-acc, val-iou


###########################################################
#                   ---   DATASETS   ---                  #
###########################################################
datasets:
    fields:
        images:
            x: raw
        labels:
            y: gt*1
        masks:
            mask: mask

    train:
        source:
            DRIVE-train-val:
              range: ':-3'

        augment:
            augmentation: default
            factor: 4

    validate:
        source:
            DRIVE-train-val:
              range: '-3:'
        cache: True

    test:
        "DRIVE":
            source: 'DRIVE-test'
            cache: True

    sources:
        DRIVE-train-val:
              dir-prefix: '/home/gaby/These/Data/Fundus/Vessels/DRIVE/train/'

              data:
                  raw:
                    type: Image
                    directory: '0-images'
                    path: '{ID:n}_training.tif'
                    clip-pad: (608, 576)

                  gt:
                    type: Mask2D
                    directory: '1-label_V'
                    path: '{ID:n}_manual1.png'
                    clip-pad: (608, 576)

                  mask:
                    type: Mask2D
                    directory: 'mask'
                    path: '{ID:n}_training_mask.png'
                    clip-pad: (608, 576)


        DRIVE-test:
              $: ..DRIVE-train-val
              dir-prefix: '/home/gaby/These/Data/Fundus/Vessels/DRIVE/test/original/'
              data:
                  raw.path: '{ID:n}_test.tif'
                  gt:
                    directory: '2-label_Vessel_1st'
                    path: '{ID:n}_manual1.png'
                  mask.path: '{ID:n}_test_mask.png'

###########################################################
#              ---   DATA-AUGMENTATIONS   ---             #
###########################################################
data-augmentation:
    default:
        flip: True
        rotation: True
        elastic:
            alpha: 40
            sigma: 20
            alpha-affine: 50
        random-crop: 512

        gamma: ±.2
        hue: ±10
        saturation: ±.1


###########################################################
#                     ---   MISC   ---                    #
###########################################################
hardware:
    debug: False
    # Select which gpus to use.
    # If you want a specific gpu put ',' after the gpu number.
    gpus: 1,
    precision: 16     # Training precision. ['64', '32', 'bf16', '16']
    cudnn-benchmark: False
    num-workers: 5
    minibatch-splits: 2

