experiment:
    name: SteeredCNN-av
    exp: RotAug
    (sub): base:none
    (id): auto
    (tags):
        ...

###########################################################
#                    ---   TASK   ---                    #
###########################################################
task:
    type: img-seg
    metrics: kappa, acc, sen, spe, iou, roc
    optimize: val-kappa
    (optimize-mode): max
    (n-classes): binary


###########################################################
#                    ---   MODEL   ---                    #
###########################################################
model:
    architecture: 'Unet'
    encoder_name: 'resnet34'
    encoder_weights: 'imagenet'
    # See https://smp.readthedocs.io/en/latest/models.html


###########################################################
#                   ---   TRAINING   ---                  #
###########################################################
training:
    loss:  cross-entropy #(eval?)

    optimizer:
        (type): Adam
        (weight_decay): 0
        (beta): 0.9       # coefficients used for computing running averages of gradient
        (beta_sqr): 0.999 # and its square
        (amsgrad): True

        lr: 1e-3

    minibatch: 8
    max-epoch: 30
    seed: 1234


###########################################################
#                   ---   DATASETS   ---                  #
###########################################################
datasets:
    fields:
        x: x
        y: "{{y}} > 1"
        mask: "{{y}} > 0"

    train:
        source: 'MESSIDOR-train'
        augment: default
        augment-factor: 2

    validate:
        source: 'MESSIDOR-val'
        cache: True

    test:
        source: 'MESSIDOR-test'
        cache: True

    sources:
        - MESSIDOR-train:
              type: ImageFolders
              path-prefix: 'PATH/train'
              paths:
                  x: 'raw/{{name}}.png'
                  y: 'gt/{{name}}.png'

        - MESSIDOR-val:
              $: ..MESSIDOR-train
              path-prefix: 'PATH/val'

        - MESSIDOR-test:
              $: ..MESSIDOR-train
              path-prefix: 'PATH/test'

###########################################################
#              ---   DATA-AUGMENTATIONS   ---             #
###########################################################
data-augmentation:
    default:
        flip: True
        rotation: True
        elastic:
            alpha: 10
            sigma: 20
            alpha-affine: 50
        crop: 512

        # gamma: ±0.2
        # hue: ±20
        # saturation: ±20


###########################################################
#                     ---   MISC   ---                    #
###########################################################
hardware:
    num-worker: auto
    half-precision: False
    minibatch-splits: 2
