experiment:
    name: SteeredCNN-av
    exp: RotAug
    (sub): base:none
    (id): auto
    (tags):
        ...


###########################################################
#         ---   HYPER-PARAMETER SEARCH   ---              #
###########################################################
optuna:
    study_name: 'test'
    sampler:
        type: TPE
        n_startup_trials: 20
    pruner:
        type: Hyperband
        
        

###########################################################
#                    ---   TASK   ---                    #
###########################################################
task:
    type: img-seg
    metrics: kappa, acc, sen, spe, iou, roc
    optimize: val-kappa
    (optimize-mode): max
    (n-classes): binary


###########################################################
#                    ---   MODEL   ---                    #
###########################################################
model:
    architecture: 'Unet'
    encoder_name: 'resnet34'
    encoder_weights: 'imagenet'
    # See https://smp.readthedocs.io/en/latest/models.html


###########################################################
#                   ---   TRAINING   ---                  #
###########################################################
training:
    loss:  cross-entropy #(eval?)

    optimizer:
        (type): Adam
        (weight_decay): 0
        (beta): 0.9       # coefficients used for computing running averages of gradient
        (beta_sqr): 0.999 # and its square
        (amsgrad): True

        lr: 1e-3

    minibatch: 8
    max-epoch: 30
    seed: 1234


###########################################################
#                   ---   DATASETS   ---                  #
###########################################################
datasets:
    fields:
        x: raw
        y: gt > 1
        mask: gt > 0

    train:
        source: DRIVE-train-val
        range: ':-3'
        augment:
            augmentation: default
            factor: 2
            images: x
            labels: y,mask

    validate:
        source: DRIVE-train-val
        range: '-3:'
        cache: True

    test:
        "MESSIDOR":
            source: 'DRIVE-test'
            cache: True

    sources:
        DRIVE-train-val:
              dir-prefix: '/home/gaby/These/Data/Fundus/Vessels/DRIVE/train/'

              data:
                  raw:
                    type: ColorMap
                    directory: '0-images'
                    path: '{ID:n}_training.png'
                    resize: 1500
                  gt:
                    type: LabelMap
                    directory: '2-label_AV'
                    $: ..raw

        DRIVE-test:
              $: ..DRIVE-train-val
              dir-prefix: 'PATH/test'

###########################################################
#              ---   DATA-AUGMENTATIONS   ---             #
###########################################################
data-augmentation:
    default:
        flip: True
        rotation: True
        elastic:
            alpha: ~optuna.float(low=1, high=50)
            sigma: 20
            alpha-affine: 50
        random-crop: 512

        # gamma: ±0.2
        # hue: ±20
        # saturation: ±20


###########################################################
#                     ---   MISC   ---                    #
###########################################################
hardware:
    num-worker: auto
    half-precision: False
    minibatch-splits: 2
